// frontend/src/components/layout/AppFooter.vue
<template>
  <footer class="footer">
    <div class="footer-glow"></div>
    <div class="container">
      <div class="footer-grid">
        <!-- Brand col -->
        <div class="footer-brand">
          <img src="@/assets/nexxus-tech-logo-full-large.svg" alt="Nexxus Tech" class="footer-logo" />
          <p class="footer-desc">
            Empowering people and organizations through consulting, architecture,
            shared knowledge, and AI-driven innovation. Inspiring growth, solving
            complex challenges, and making expertise more accessible.
          </p>
          <div class="footer-social">
            <SocialLinks variant="icons" />
          </div>
        </div>

        <!-- Services col -->
        <nav class="footer-col" aria-label="Services">
          <h3 class="footer-col-title">Services</h3>
          <ul>
            <li><RouterLink to="/services#waf">WAF & API Protection</RouterLink></li>
            <li><RouterLink to="/services#netscaler">NetScaler / ADC</RouterLink></li>
            <li><RouterLink to="/services#zerotrust">Zero-Trust Architecture</RouterLink></li>
            <li><RouterLink to="/services#cloud">Cloud Security</RouterLink></li>
            <li><RouterLink to="/services#ai">AI & Automation</RouterLink></li>
          </ul>
        </nav>

        <!-- Products col -->
        <nav class="footer-col" aria-label="Products">
          <h3 class="footer-col-title">Products</h3>
          <ul>
            <li><RouterLink to="/products#jpilot">JPilot</RouterLink></li>
            <li><RouterLink to="/products">All Products</RouterLink></li>
          </ul>
        </nav>

        <!-- Company col -->
        <nav class="footer-col" aria-label="Company">
          <h3 class="footer-col-title">Company</h3>
          <ul>
            <li><RouterLink to="/about">About Us</RouterLink></li>
            <li><RouterLink to="/faq">FAQ</RouterLink></li>
            <li><RouterLink to="/blog">Blog & Insights</RouterLink></li>
            <li><RouterLink to="/contact">Contact</RouterLink></li>
          </ul>
        </nav>

        <!-- Legal col -->
        <nav class="footer-col" aria-label="Legal">
          <h3 class="footer-col-title">Legal</h3>
          <ul>
            <li>
              <a href="https://jpilot.nexxus-tech.com/legal/privacy">Privacy</a>
            </li>
            <li>
              <a href="https://jpilot.nexxus-tech.com/legal/terms">Terms of Use</a>
            </li>
          </ul>
        </nav>

        <!-- Contact col -->
        <div class="footer-col">
          <h3 class="footer-col-title">Contact</h3>
          <ul class="contact-list">
            <li>
              <i class="pi pi-envelope"></i>
              <a href="mailto:contact@nexxus-tech.com">contact@nexxus-tech.com</a>
            </li>
            <li>
              <i class="pi pi-globe"></i>
              <span>nexxus-tech.com</span>
            </li>
            <li>
              <i class="pi pi-map-marker"></i>
              <span>Colombia · UAE · UK · US</span>
            </li>
          </ul>
        </div>
      </div>

      <div class="footer-bottom">
        <p>&copy; {{ new Date().getFullYear() }} Nexxus Tech. All rights reserved.</p>
        <p class="footer-bottom-right">
          Specialized in <span class="highlight">WAF</span> ·
          <span class="highlight">NetScaler</span> ·
          <span class="highlight">Cloud Security</span> ·
          <span class="highlight">AI</span>
        </p>
      </div>
    </div>
  </footer>
</template>

<script setup>
import SocialLinks from '@/components/shared/SocialLinks.vue'
</script>

<style scoped>
.footer {
  background: var(--nt-dark-2);
  border-top: 1px solid var(--nt-border);
  padding: 80px 0 0;
  position: relative;
  overflow: hidden;
}
.footer-glow {
  position: absolute;
  top: -100px; left: 50%;
  transform: translateX(-50%);
  width: 600px; height: 200px;
  background: radial-gradient(ellipse, rgba(91,79,232,0.12) 0%, transparent 70%);
  pointer-events: none;
}
.footer-grid {
  display: grid;
  grid-template-columns: 2fr repeat(4, 1fr) 1.25fr;
  gap: 32px;
  margin-bottom: 60px;
}
.footer-logo { height: 48px; width: auto; margin-bottom: 20px; display: block; }
.footer-desc {
  font-size: 0.9rem;
  color: var(--nt-text-muted);
  line-height: 1.7;
  margin-bottom: 24px;
  max-width: 320px;
}
.footer-social { display: flex; gap: 10px; }
.social-btn {
  width: 48px; height: 48px;
  min-width: 48px;
  min-height: 48px;
  border-radius: 8px;
  background: rgba(255,255,255,0.04);
  border: 1px solid rgba(255,255,255,0.08);
  display: flex; align-items: center; justify-content: center;
  color: var(--nt-text-muted);
  font-size: 1rem;
  transition: var(--nt-transition);
  text-decoration: none;
}
.social-btn:hover {
  background: var(--nt-primary);
  border-color: var(--nt-primary);
  color: white;
  transform: translateY(-2px);
}
.footer-col-title {
  font-family: var(--font-heading);
  font-size: 0.8rem;
  font-weight: 700;
  letter-spacing: 0.15em;
  text-transform: uppercase;
  color: var(--nt-secondary);
  margin-bottom: 20px;
}
.footer-col ul { list-style: none; display: flex; flex-direction: column; gap: 10px; }
.footer-col ul li a,
.footer-col ul li span {
  font-size: 0.9rem;
  color: var(--nt-text-muted);
  text-decoration: none;
  transition: color 0.2s;
}
.footer-col ul li a:hover { color: var(--nt-white); }
.contact-list { gap: 14px !important; }
.contact-list li {
  display: flex;
  align-items: center;
  gap: 10px;
}
.contact-list .pi {
  color: var(--nt-primary-l);
  font-size: 0.9rem;
  flex-shrink: 0;
}
.footer-bottom {
  border-top: 1px solid rgba(255,255,255,0.06);
  padding: 24px 0;
  display: flex;
  justify-content: space-between;
  align-items: center;
  font-size: 0.85rem;
  color: var(--nt-text-muted);
  flex-wrap: wrap;
  gap: 8px;
}
.highlight { color: var(--nt-secondary); }

@media (max-width: 1024px) {
  .footer-grid { grid-template-columns: 1fr 1fr; }
}
@media (max-width: 600px) {
  .footer-grid { grid-template-columns: 1fr; gap: 32px; }
  .footer-bottom { flex-direction: column; text-align: center; }
  .footer-bottom-right { display: none; }
}
</style>

// frontend-react/src/components/layout/AppFooter.tsx
import { Link } from 'react-router-dom'
import { ExternalLink } from 'lucide-react'

const footerLinks = {
  services: [
    { to: '/services#waf', label: 'WAF & API Protection' },
    { to: '/services#netscaler', label: 'NetScaler / ADC' },
    { to: '/services#zerotrust', label: 'Zero-Trust Architecture' },
    { to: '/services#cloud', label: 'Cloud Security' },
    { to: '/services#ai', label: 'AI & Automation' },
  ],
  products: [
    { to: '/products#jpilot', label: 'JPilot' },
    { to: '/products', label: 'All Products' },
  ],
  company: [
    { to: '/about', label: 'About Us' },
    { to: '/faq', label: 'FAQ' },
    { to: '/blog', label: 'Blog & Insights' },
    { to: '/book-demo', label: 'Book a Demo' },
    { to: '/contact', label: 'Contact' },
  ],
}

export default function AppFooter() {
  return (
    <footer className="relative border-t border-[var(--nt-border)] bg-[var(--nt-dark-2)] pt-16 pb-8">
      <div className="pointer-events-none absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-[var(--nt-primary)] to-transparent opacity-40" />
      <div className="container">
        <div className="grid gap-10 md:grid-cols-2 lg:grid-cols-6">
          <div className="lg:col-span-2">
            <img
              src="/nexxus-tech-logo-full-large.svg"
              alt="Nexxus Tech"
              className="mb-4 h-10 w-auto"
            />
            <p className="mb-6 max-w-sm text-sm leading-relaxed text-[var(--nt-text-muted)]">
              Empowering people and organizations through consulting, architecture,
              shared knowledge, and AI-driven innovation.
            </p>
            <div className="flex gap-3">
              <a
                href="https://www.linkedin.com/in/jotalvaro/"
                target="_blank"
                rel="noopener noreferrer"
                className="flex h-10 w-10 items-center justify-center rounded-lg border border-[var(--nt-border)] text-[var(--nt-secondary)] transition-colors hover:border-[var(--nt-primary)] hover:text-[var(--nt-primary-l)]"
                aria-label="LinkedIn"
              >
                <ExternalLink className="h-4 w-4" />
              </a>
              <a
                href="https://github.com/juandiab"
                target="_blank"
                rel="noopener noreferrer"
                className="flex h-10 w-10 items-center justify-center rounded-lg border border-[var(--nt-border)] text-[var(--nt-secondary)] transition-colors hover:border-[var(--nt-primary)] hover:text-[var(--nt-primary-l)]"
                aria-label="GitHub"
              >
                <ExternalLink className="h-4 w-4" />
              </a>
            </div>
          </div>

          <FooterCol title="Services" links={footerLinks.services} />
          <FooterCol title="Products" links={footerLinks.products} />
          <FooterCol title="Company" links={footerLinks.company} />

          <div>
            <h3 className="mb-4 font-[family-name:var(--font-heading)] text-xs font-bold tracking-widest text-white uppercase">
              Contact
            </h3>
            <ul className="space-y-3 text-sm text-[var(--nt-text-muted)]">
              <li>
                <a href="mailto:contact@nexxus-tech.com" className="hover:text-[var(--nt-secondary)]">
                  contact@nexxus-tech.com
                </a>
              </li>
              <li>nexxus-tech.com</li>
              <li>Colombia · UAE · UK · US</li>
            </ul>
          </div>
        </div>

        <div className="mt-12 flex flex-col items-center justify-between gap-4 border-t border-[var(--nt-border)] pt-8 text-sm text-[var(--nt-text-muted)] md:flex-row">
          <p>© {new Date().getFullYear()} Nexxus Tech. All rights reserved.</p>
          <div className="flex gap-6">
            <a href="https://jpilot.nexxus-tech.com/legal/privacy">Privacy</a>
            <a href="https://jpilot.nexxus-tech.com/legal/terms">Terms of Use</a>
          </div>
        </div>
      </div>
    </footer>
  )
}

function FooterCol({
  title,
  links,
}: {
  title: string
  links: { to: string; label: string }[]
}) {
  return (
    <nav aria-label={title}>
      <h3 className="mb-4 font-[family-name:var(--font-heading)] text-xs font-bold tracking-widest text-white uppercase">
        {title}
      </h3>
      <ul className="space-y-2.5">
        {links.map((link) => (
          <li key={link.to}>
            <Link
              to={link.to}
              className="text-sm text-[var(--nt-text-muted)] transition-colors hover:text-[var(--nt-secondary)]"
            >
              {link.label}
            </Link>
          </li>
        ))}
      </ul>
    </nav>
  )
}
