// frontend/src/components/layout/NavBar.vue
<template>
  <header :class="['navbar', { scrolled: isScrolled, 'menu-open': menuOpen }]">
    <div class="container navbar-inner">
      <!-- Logo -->
      <RouterLink to="/" class="navbar-logo" @click="menuOpen = false">
        <img :src="logoSrc" alt="Nexxus Tech" class="logo-img" width="324" height="52" decoding="async" />
      </RouterLink>

      <!-- Desktop nav -->
      <nav class="navbar-links" aria-label="Main navigation">
        <RouterLink v-for="link in links" :key="link.to" :to="link.to" class="nav-link">
          {{ link.label }}
        </RouterLink>
        <RouterLink to="/contact" class="btn btn-primary nav-cta">Get in Touch</RouterLink>
      </nav>

      <!-- Mobile hamburger -->
      <button class="hamburger" @click="menuOpen = !menuOpen" aria-label="Toggle menu">
        <span :class="{ open: menuOpen }"></span>
        <span :class="{ open: menuOpen }"></span>
        <span :class="{ open: menuOpen }"></span>
      </button>
    </div>

    <!-- Mobile menu -->
    <Transition name="mobile-menu">
      <div v-if="menuOpen" class="mobile-nav" role="navigation" aria-label="Mobile navigation">
        <RouterLink
          v-for="link in links"
          :key="link.to"
          :to="link.to"
          class="mobile-nav-link"
          @click="menuOpen = false"
        >
          {{ link.label }}
        </RouterLink>
        <RouterLink to="/contact" class="btn btn-primary w-full" @click="menuOpen = false">
          Get in Touch
        </RouterLink>
      </div>
    </Transition>
  </header>
</template>

<script setup>
import { ref, onMounted, onUnmounted } from 'vue'
import logo from '@/assets/nexxus-tech-logo-full-large.svg'

const isScrolled = ref(false)
const menuOpen = ref(false)
const logoSrc = logo

const links = [
  { to: '/', label: 'Home' },
  { to: '/services', label: 'Services' },
  { to: '/products', label: 'Products' },
  { to: '/about', label: 'About' },
  { to: '/blog', label: 'Blog' },
  { to: '/book-demo', label: 'Book a Demo' },
]

const onScroll = () => { isScrolled.value = window.scrollY > 40 }
onMounted(() => window.addEventListener('scroll', onScroll, { passive: true }))
onUnmounted(() => window.removeEventListener('scroll', onScroll))
</script>

<style scoped>
.navbar {
  position: fixed;
  top: 0; left: 0; right: 0;
  z-index: 1000;
  transition: background 0.35s ease, box-shadow 0.35s ease;
  background: transparent;
  padding: 8px 0;
  min-height: 88px;
}
.navbar.scrolled {
  background: rgba(28, 28, 30, 0.95);
  backdrop-filter: blur(16px);
  box-shadow: 0 1px 0 rgba(0, 123, 167, 0.15);
}
.navbar-inner {
  display: flex;
  align-items: center;
  justify-content: space-between;
  height: 72px;
}
.navbar-logo { display: flex; align-items: center; }
.logo-img { height: 52px; width: 324px; max-width: 100%; display: block; }

.navbar-links {
  display: flex;
  align-items: center;
  gap: 8px;
}
.nav-link {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-height: 48px;
  min-width: 48px;
  font-family: var(--font-heading);
  font-size: 0.85rem;
  font-weight: 600;
  letter-spacing: 0.06em;
  text-transform: uppercase;
  color: rgba(255,255,255,0.75);
  padding: 8px 16px;
  border-radius: 6px;
  transition: var(--nt-transition);
  text-decoration: none;
}
.nav-link:hover,
.nav-link.router-link-active {
  color: var(--nt-white);
  background: rgba(0, 123, 167, 0.12);
}
.nav-cta { margin-left: 8px; padding: 10px 24px; font-size: 0.85rem; }

/* Hamburger */
.hamburger {
  display: none;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 5px;
  min-width: 48px;
  min-height: 48px;
  background: none;
  border: none;
  cursor: pointer;
  padding: 6px;
}
.hamburger span {
  display: block;
  width: 26px;
  height: 2px;
  background: var(--nt-white);
  border-radius: 2px;
  transition: var(--nt-transition);
  transform-origin: center;
}
.hamburger span.open:nth-child(1) { transform: rotate(45deg) translate(5px, 5px); }
.hamburger span.open:nth-child(2) { opacity: 0; transform: scaleX(0); }
.hamburger span.open:nth-child(3) { transform: rotate(-45deg) translate(5px, -5px); }

/* Mobile menu */
.mobile-nav {
  display: flex;
  flex-direction: column;
  gap: 4px;
  padding: 16px 24px 24px;
  background: rgba(28, 28, 30, 0.98);
  border-top: 1px solid rgba(0, 123, 167, 0.15);
}
.mobile-nav-link {
  display: flex;
  align-items: center;
  min-height: 48px;
  font-family: var(--font-heading);
  font-size: 1rem;
  font-weight: 600;
  color: rgba(255,255,255,0.8);
  padding: 14px 16px;
  border-radius: 8px;
  text-decoration: none;
  transition: var(--nt-transition);
}
.mobile-nav-link:hover { color: white; background: rgba(0,123,167,0.15); }
.w-full { width: 100%; justify-content: center; margin-top: 8px; }

/* Transition */
.mobile-menu-enter-active, .mobile-menu-leave-active { transition: all 0.3s ease; }
.mobile-menu-enter-from, .mobile-menu-leave-to { opacity: 0; transform: translateY(-10px); }

@media (max-width: 768px) {
  .navbar-links { display: none; }
  .hamburger { display: flex; }
}
</style>

// frontend-react/src/components/layout/NavBar.tsx
import { useEffect, useState } from 'react'
import { Link, NavLink } from 'react-router-dom'
import { Menu } from 'lucide-react'
import { buttonVariants } from '@/components/ui/button'
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from '@/components/ui/sheet'
import { cn } from '@/lib/utils'

const links = [
  { to: '/', label: 'Home' },
  { to: '/services', label: 'Services' },
  { to: '/products', label: 'Products' },
  { to: '/about', label: 'About' },
  { to: '/blog', label: 'Blog' },
  { to: '/book-demo', label: 'Book a Demo' },
]

export default function NavBar() {
  const [scrolled, setScrolled] = useState(false)
  const [open, setOpen] = useState(false)

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 40)
    window.addEventListener('scroll', onScroll, { passive: true })
    return () => window.removeEventListener('scroll', onScroll)
  }, [])

  return (
    <header
      className={`fixed top-0 left-0 right-0 z-50 transition-all duration-300 ${
        scrolled
          ? 'bg-[rgba(28,28,30,0.95)] backdrop-blur-md shadow-[0_1px_0_rgba(0,123,167,0.15)]'
          : 'bg-transparent'
      }`}
    >
      <div className="container flex h-[72px] items-center justify-between">
        <Link to="/" className="flex items-center" onClick={() => setOpen(false)}>
          <img
            src="/nexxus-tech-logo-full-large.svg"
            alt="Nexxus Tech"
            className="h-[52px] w-auto max-w-full"
            width={324}
            height={52}
            decoding="async"
          />
        </Link>

        <nav className="hidden items-center gap-1 lg:flex" aria-label="Main navigation">
          {links.map((link) => (
            <NavLink
              key={link.to}
              to={link.to}
              className={({ isActive }) =>
                `inline-flex min-h-12 min-w-12 items-center justify-center rounded-md px-4 py-2 font-[family-name:var(--font-heading)] text-[0.85rem] font-semibold tracking-wider uppercase transition-colors ${
                  isActive
                    ? 'text-white'
                    : 'text-white/75 hover:text-white'
                }`
              }
            >
              {link.label}
            </NavLink>
          ))}
          <Link
            to="/contact"
            className={cn(
              buttonVariants({ variant: 'default' }),
              'ml-2 bg-[var(--nt-primary)] hover:bg-[var(--nt-primary-l)]'
            )}
          >
            Get in Touch
          </Link>
        </nav>

        <Sheet open={open} onOpenChange={setOpen}>
          <SheetTrigger
            className={cn(buttonVariants({ variant: 'ghost', size: 'icon' }), 'lg:hidden')}
            aria-label="Toggle menu"
          >
            <Menu className="h-6 w-6 text-white" />
          </SheetTrigger>
          <SheetContent side="right" className="border-[var(--nt-border)] bg-[var(--nt-dark)]">
            <SheetHeader>
              <SheetTitle className="text-white">Menu</SheetTitle>
            </SheetHeader>
            <nav className="mt-8 flex flex-col gap-2" aria-label="Mobile navigation">
              {links.map((link) => (
                <Link
                  key={link.to}
                  to={link.to}
                  onClick={() => setOpen(false)}
                  className="rounded-md px-4 py-3 font-[family-name:var(--font-heading)] text-sm font-semibold tracking-wider text-white/80 uppercase hover:bg-white/5 hover:text-white"
                >
                  {link.label}
                </Link>
              ))}
              <Link
                to="/contact"
                onClick={() => setOpen(false)}
                className={cn(
                  buttonVariants({ variant: 'default' }),
                  'mt-4 w-full bg-[var(--nt-primary)] text-center'
                )}
              >
                Get in Touch
              </Link>
            </nav>
          </SheetContent>
        </Sheet>
      </div>
    </header>
  )
}
